// api/auto-brief.js
// Vercel cron job — runs weekdays at 12:30 UTC (7:30 EST / 8:30 EDT)
// Generates macro briefs for ES, Gold, Oil and Euro
// then emails all 4 formatted tweets to Elvis ready to copy-paste.
//
// Required environment variables (set in Vercel dashboard):
//   ANTHROPIC_API_KEY   — your existing Claude API key
//   LOOPS_API_KEY       — your existing Loops API key

export const config = {
  maxDuration: 60,
};

// ── INSTRUMENTS TO BRIEF DAILY ────────────────────────────────────────────────
const DAILY_INSTRUMENTS = [
  { key: "es",   label: "ES S&P 500",    hashtags: "#ES #SPX" },
  { key: "gold", label: "Gold XAU/USD",  hashtags: "#Gold #XAUUSD" },
  { key: "oil",  label: "WTI Crude Oil", hashtags: "#Oil #CrudeOil" },
  { key: "euro", label: "EUR/USD",       hashtags: "#EURUSD #Forex" },
];

const DELIVERY_EMAIL = "elviskotungondo@gmail.com";

// ── SYSTEM PROMPT ─────────────────────────────────────────────────────────────
function tweetSysPrompt() {
  return `You are a macro market analyst writing ultra-concise daily briefings for traders on X.
Respond ONLY with valid JSON. No markdown, no backticks, no preamble. Start with { and end with }.
CRITICAL: Every field must be 50 characters or less — this formats into a tweet with a hard 280 char limit.
RULES:
1. Never mention specific price levels, targets, or stops.
2. Focus only on CURRENT macro — central bank stance, live risk, next event.
3. bias_reason must be 40 chars or less.
SCHEMA: {"instrument":"string","bias":"BULLISH|BEARISH|NEUTRAL","bias_reason":"string","central_bank":"string","key_risk":"string","next_event":"string"}`;
}

function tweetUserPrompt(label) {
  const now = new Date().toLocaleString("en-GB", {
    weekday: "long", year: "numeric", month: "long",
    day: "numeric", hour: "2-digit", minute: "2-digit",
    timeZone: "America/New_York",
  });
  return `Time: ${now} EST. Ultra-concise tweet-ready macro brief for ${label}. Each field max 50 chars. No price levels. Current central bank stance, biggest risk right now, next high-impact event.`;
}

// ── GENERATE BRIEF VIA CLAUDE ─────────────────────────────────────────────────
async function generateTweetBrief(label) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-20250514",
      max_tokens: 300,
      system: tweetSysPrompt(),
      messages: [{ role: "user", content: tweetUserPrompt(label) }],
    }),
  });

  if (!res.ok) throw new Error(`Claude API error: ${res.status}`);
  const data = await res.json();
  const text = (data.content || [])
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("");
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) throw new Error("No JSON in Claude response");
  return JSON.parse(match[0]);
}

// ── FORMAT BRIEF INTO TWEET TEXT ──────────────────────────────────────────────
function formatTweet(brief, hashtags) {
  const biasEmoji = { BULLISH: "🟢", BEARISH: "🔴", NEUTRAL: "🟡" };
  const emoji = biasEmoji[brief.bias] || "🟡";
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "short",
    timeZone: "America/New_York",
  });

  const truncate = (str, max) =>
    str && str.length > max ? str.slice(0, max - 1) + "…" : str;

  const tweet = `${brief.instrument} — ${date}

🏦 ${truncate(brief.central_bank, 50)}
⚠️ ${truncate(brief.key_risk, 50)}
📅 ${truncate(brief.next_event, 50)}
${emoji} ${brief.bias} — ${truncate(brief.bias_reason, 40)}

marketdebriefs.com
${hashtags} #MacroTrading`;

  return tweet.length > 275 ? tweet.slice(0, 272) + "…" : tweet;
}

// ── FORMAT ALL TWEETS INTO PLAIN TEXT FOR EMAIL ───────────────────────────────
// Loops event properties have a size limit so we use plain text not HTML
function buildEmailText(tweets) {
  const lines = [];
  lines.push("Your 4 macro posts for today — copy and post to @MarketDebriefs\n");
  lines.push("=".repeat(50));

  tweets.forEach(({ label, tweet, status }) => {
    lines.push("\n" + label.toUpperCase());
    lines.push("-".repeat(30));
    if (status === "failed") {
      lines.push("Brief generation failed — run manually.");
    } else {
      lines.push(tweet);
      lines.push(`(${tweet.length}/280 chars)`);
    }
  });

  lines.push("\n" + "=".repeat(50));
  lines.push("Generated by MarketDebriefs · marketdebriefs.com");
  return lines.join("\n");
}

// ── SEND EMAIL VIA LOOPS TRANSACTIONAL ───────────────────────────────────────
async function sendEmail(tweets, date) {
  const t = tweets;
  const res = await fetch("https://app.loops.so/api/v1/transactional", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${process.env.LOOPS_API_KEY}`,
    },
    body: JSON.stringify({
      transactionalId: "daily_macro_posts",
      email: DELIVERY_EMAIL,
      dataVariables: {
        date,
        post1_label: t[0] ? t[0].label : "",
        post1_text:  t[0] ? t[0].tweet : "Failed",
        post2_label: t[1] ? t[1].label : "",
        post2_text:  t[1] ? t[1].tweet : "Failed",
        post3_label: t[2] ? t[2].label : "",
        post3_text:  t[2] ? t[2].tweet : "Failed",
        post4_label: t[3] ? t[3].label : "",
        post4_text:  t[3] ? t[3].tweet : "Failed",
      },
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Loops email error ${res.status}: ${err}`);
  }

  return res.json();
}

// ── MAIN HANDLER ──────────────────────────────────────────────────────────────
export default async function handler(req, res) {

  const isCron = req.headers["x-vercel-cron"] === "1";
  const isManualTest = req.method === "POST" &&
    req.headers["x-manual-trigger"] === process.env.ANTHROPIC_API_KEY;

  if (!isCron && !isManualTest) {
    return res.status(401).json({ error: "Unauthorised" });
  }

  // Skip weekends
  const day = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    timeZone: "America/New_York",
  });
  if (day === "Saturday" || day === "Sunday") {
    console.log("Weekend — skipping auto-brief");
    return res.status(200).json({ ok: true, skipped: "weekend" });
  }

  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "short",
    timeZone: "America/New_York",
  });

  console.log(`Auto-brief starting — ${new Date().toISOString()}`);

  const tweets = [];

  for (const { label, hashtags } of DAILY_INSTRUMENTS) {
    try {
      console.log(`Generating brief for ${label}...`);
      const brief = await generateTweetBrief(label);
      const tweet = formatTweet(brief, hashtags);
      console.log(`Brief ready for ${label} — ${tweet.length} chars`);
      tweets.push({ label, tweet, status: "ok" });
    } catch (err) {
      console.error(`Failed for ${label}:`, err.message);
      tweets.push({ label, tweet: "", status: "failed" });
    }
  }

  try {
    console.log("Building and sending email...");
    await sendEmail(tweets, date);
    console.log(`Email sent to ${DELIVERY_EMAIL}`);
  } catch (err) {
    console.error("Email send failed:", err.message);
    return res.status(500).json({ ok: false, error: err.message });
  }

  const results = tweets.map(({ label, status, tweet }) => ({
    instrument: label,
    status,
    chars: tweet.length,
  }));

  console.log("Auto-brief complete:", results);
  return res.status(200).json({ ok: true, results, emailSent: true });
}
